import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-full">
			<body
				className={
					inter.className +
					"w-full h-full grid grid-rows-[auto_1fr_auto] grid-cols-1"
				}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
